Added support for footer in embed block as a manual attribute
phenom4n4n/TagScript pull request #15
Opened 2023-03-12 09:13 UTC by sravan1946

This pr also fixes a bug in `helper_split` and also adds hyperbolic funtions to math block

2023-03-12 18:52 UTC, sravan1946 commented
made the hyperbolic funtions into the seperate pr

2023-03-13 03:09 UTC, phenom4n4n requested changes

2023-03-13 03:09 UTC, phenom4n4n commented on TagScriptEngine/block/helpers.py
> +    return split_string
The helper method is only supposed to return a list of strings. This change breaks the behavior of other blocks because of the new return type.

2023-03-13 03:09 UTC, phenom4n4n commented on TagScriptEngine/block/helpers.py
> +    return split_string
I would modify the `set_footer `method to handle when `helper_split `returns `None`, rather than modifying the method itself.

2023-03-13 15:36 UTC, phenom4n4n approved these changes

2023-03-13 15:36 UTC, merged